"""
Django settings for Investment project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decimal import Decimal
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv(BASE_DIR / 'Investment' / '.env')

def get_env_value(env_variable):
    """Get the environment variable or return exception"""
    try:
        return os.environ[env_variable]
    except KeyError:
        error_msg = f'Set the {env_variable} environment variable'
        raise ImproperlyConfigured(error_msg)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yy90w5ujb3(ke8%@qio1(@#t6uq7w^4uk))2!s%44^^*m$-i#m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')

# Payment settings
MIN_DEPOSIT_AMOUNT = Decimal(os.getenv('MIN_DEPOSIT_AMOUNT', '10.00'))
MAX_DEPOSIT_AMOUNT = Decimal(os.getenv('MAX_DEPOSIT_AMOUNT', '50000.00'))

ALLOWED_HOSTS = ['*', 'https://arbitrageflow.onrender.com', 'arbitrageflow.online']

CSRF_TRUSTED_ORIGINS = [
    'https://arbitrageflow.onrender.com',
    'https://arbitrageflow.online',
    ]

AUTH_USER_MODEL = 'account.User'

# Application definition
INSTALLED_APPS = [
    # Jazzmin Admin Interface (must be before django.contrib.admin)
    'jazzmin',
    
    # Django Core Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Project Apps
    'account',
    'core',
]

MIDDLEWARE = [
    # WhiteNoise middleware (should be near the top, after security middleware)
    
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Investment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.complete_expired_investments',
            ],
        },
    },
]

WSGI_APPLICATION = 'Investment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Add these at the top of your settings.py
from urllib.parse import urlparse, parse_qsl


# Replace the DATABASES section of your settings.py with this
tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpPostgres.path.replace('/', ''),
        'USER': tmpPostgres.username,
        'PASSWORD': tmpPostgres.password,
        'HOST': tmpPostgres.hostname,
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Collected static files for production
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Additional locations of static files
]

# WhiteNoise Configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication Settings
LOGIN_URL = 'account:login'  # URL where requests are redirected for login, pointing to account app's login view
LOGIN_REDIRECT_URL = 'account:dashboard'  # URL to redirect after login when no next parameter is given
LOGOUT_REDIRECT_URL = 'account:login'  # URL to redirect after logout
LOGOUT_URL = 'account:logout'  # URL for the logout view

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# ==========================================
# JAZZMIN ADMIN CONFIGURATION
# ==========================================

JAZZMIN_SETTINGS = {
    # Admin site header and title
    "site_title": "ArbitrageFlow Admin",
    "site_header": "ArbitrageFlow",
    "site_brand": "ArbitrageFlow",
    
    # Admin interface colors and styling
    "welcome_sign": "Welcome to ArbitrageFlow Admin Dashboard",
    "copyright": "ArbitrageFlow © 2026. All rights reserved.",
    
    # Dashboard configuration
    "order_with_respect_to": [
        "auth",
        "account",
        "core",
    ],
    
    # Icons for apps and models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "account.user": "fas fa-user-tie",
        "account.profile": "fas fa-id-card",
        "core.investment": "fas fa-chart-line",
        "core.investmentplan": "fas fa-briefcase",
        "core.deposit": "fas fa-money-bill-wave",
        "core.withdrawal": "fas fa-wallet",
    },
    
    # Customization options
    "default_icon_parents": "fas fa-chevron-right",
    "default_icon_children": "fas fa-arrow-right",
    
    # Search configuration
    "search_model": "auth.user",
    
    # Admin user model
    "user_avatar": None,
    
    # Appearance
    "show_ui_builder": True,
    "ui_tweaks": {
        "navbar_small": False,
        "footer_small": False,
        "body_small": False,
        "brand_small": False,
        "sidebar_nav_small": False,
    },
    
    # Analytics
    "show_perf_icons": True,
    "perf_icons": {
        "cpu": "fas fa-server",
        "memory": "fas fa-microchip",
        "queries": "fas fa-database",
    },
}

# Jazzmin Admin Customizations
JAZZMIN_UI_TWEAKS = {
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "brand_small": False,
    "sidebar_nav_small": False,
    "sidebar_disable_expand": False,
}

# ==========================================
# PRODUCTION SECURITY SETTINGS
# ==========================================

# Update these settings when moving to production:

# SECURITY WARNING: Change debug to False in production!
# DEBUG = False

# SECURITY WARNING: Update ALLOWED_HOSTS in production!
# ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com']

# SECURITY WARNING: Use proper database in production (PostgreSQL recommended)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'arbitrageflow_db',
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST'),
#         'PORT': os.getenv('DB_PORT', '5432'),
#     }
# }

# HTTPS and Security settings for production:
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_SECURITY_POLICY = {
#     "default-src": ("'self'",),
#     "script-src": ("'self'", "'unsafe-inline'", "cdn.jsdelivr.net"),
#     "style-src": ("'self'", "'unsafe-inline'", "fonts.googleapis.com", "cdn.jsdelivr.net"),
#     "font-src": ("'self'", "fonts.gstatic.com"),
#     "img-src": ("'self'", "data:", "https:"),
# }

# Email configuration for production:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv('EMAIL_HOST')
# EMAIL_PORT = os.getenv('EMAIL_PORT', 587)
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
